/**
 * Reusable Cloudflare Pages asset guard + SPA document shell helper.
 * Used by generated _worker.js and unit tests.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TEMPLATES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "templates");

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function prefixToRegex(prefix) {
  const normalized = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix;
  return new RegExp(`^${escapeRegex(normalized)}(?:/|$)`);
}

export function createPagesGuard(options = {}) {
  const staticPrefixes = (options.staticPrefixes || ["/assets/"]).map((prefix) =>
    prefix.endsWith("/") ? prefix : `${prefix}/`,
  );
  const spaPrefixes = (options.spaPrefixes || []).map((prefix) =>
    prefix.endsWith("/") ? prefix : `${prefix}/`,
  );
  const spaStaticPrefixes = (options.spaStaticPrefixes || []).map((prefix) =>
    prefix.endsWith("/") ? prefix : `${prefix}/`,
  );

  const staticMatchers = staticPrefixes.map(prefixToRegex);
  const spaMatchers = spaPrefixes.map((prefix) => ({
    prefix,
    matcher: prefixToRegex(prefix),
  }));
  const spaStaticMatchers = spaStaticPrefixes.map(prefixToRegex);

  function isStaticPath(pathname) {
    return staticMatchers.some((matcher) => matcher.test(pathname));
  }

  function isSpaStaticPath(pathname) {
    return spaStaticMatchers.some((matcher) => matcher.test(pathname));
  }

  function findSpaShellPrefix(pathname) {
    for (const entry of spaMatchers) {
      if (
        entry.matcher.test(pathname) &&
        !isStaticPath(pathname) &&
        !isSpaStaticPath(pathname) &&
        !pathname.includes(".")
      ) {
        return entry.prefix;
      }
    }
    return null;
  }

  function missingAssetResponse(request) {
    return new Response(request.method === "HEAD" ? null : "Asset not found", {
      status: 404,
      headers: {
        "Cache-Control": "no-store",
        "Content-Type": "text/plain; charset=utf-8",
        "X-Content-Type-Options": "nosniff",
      },
    });
  }

  return {
    async fetch(request, env) {
      const url = new URL(request.url);
      const isDocumentRequest = request.method === "GET" || request.method === "HEAD";
      const spaShellPrefix = isDocumentRequest ? findSpaShellPrefix(url.pathname) : null;

      if (spaShellPrefix) {
        const documentUrl = new URL(spaShellPrefix, url);
        const response = await env.ASSETS.fetch(new Request(documentUrl, request));
        const headers = new Headers(response.headers);
        headers.set("Cache-Control", "no-cache");
        return new Response(response.body, {
          status: response.status,
          statusText: response.statusText,
          headers,
        });
      }

      const response = await env.ASSETS.fetch(request);

      if (isStaticPath(url.pathname)) {
        const contentType = response.headers.get("content-type") || "";
        if (contentType.toLowerCase().startsWith("text/html")) {
          return missingAssetResponse(request);
        }
      }

      return response;
    },
  };
}

export function generateWorkerSource(config) {
  const payload = {
    staticPrefixes: config.staticPrefixes,
    spaPrefixes: config.spaPrefixes,
    spaStaticPrefixes: config.spaStaticPrefixes,
  };
  const runtime = readFileSync(join(TEMPLATES_DIR, "worker-runtime.js"), "utf8");

  return [
    "/* Generated by caddie cloudflare:pages:setup — do not edit by hand unless you know why. */",
    `const GUARD_OPTIONS = ${JSON.stringify(payload, null, 2)};`,
    "",
    runtime,
  ].join("\n");
}

export function generateRoutesConfig(config) {
  const include = new Set();
  const exclude = new Set();

  for (const prefix of config.staticPrefixes || []) {
    const trimmed = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix;
    include.add(`${trimmed}/*`);
  }

  for (const prefix of config.spaPrefixes || []) {
    const trimmed = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix;
    include.add(trimmed);
    include.add(`${trimmed}/*`);
  }

  for (const prefix of config.spaStaticPrefixes || []) {
    const trimmed = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix;
    const normalizedSpaStatic = prefix.endsWith("/") ? prefix : `${prefix}/`;
    const guarded = (config.staticPrefixes || []).some((staticPrefix) => {
      const normalizedStatic = staticPrefix.endsWith("/") ? staticPrefix : `${staticPrefix}/`;
      return (
        normalizedStatic === normalizedSpaStatic ||
        normalizedStatic.startsWith(normalizedSpaStatic) ||
        normalizedSpaStatic.startsWith(normalizedStatic)
      );
    });
    if (!guarded) {
      exclude.add(`${trimmed}/*`);
    }
  }

  return {
    version: 1,
    include: [...include],
    exclude: [...exclude],
  };
}
